### ISSUE TITLE
[ INFO] [1487222698.043716432, 2244.557000000]: Failed to subtract global_frame (/map) from odom_frame (/odom)

### ISSUE THREAD

**Issue by andrestoga** [mrpt-ros-pkg/mrpt_slam#19]
Hi,

I'm getting the following error when I feed the topic /landmark with observations:

`[ INFO] [1487222698.043716432, 2244.557000000]: Failed to subtract global_frame (/map) from odom_frame (/odom)`

Plus I cannot get the transformation from base_link to map:

Exception thrown:Lookup would require extrapolation into the past.  Requested time 0.100000000 but the earliest data is at time 2717.133000000, when looking up transform from frame [base_link] to frame [map]

I don't know why the Most recent transform and the oldest transform of the map frame is always 0.1:

http://imgur.com/a/remCB

Best,

**Comment by andrestoga** [comment]
Seems like getting the time in method EKFslamWrapper::landmarkCallback

`185 timeLastUpdate_ = sf->getObservationByIndex(0)->timestamp;`

is setting a value different to the one of the observation and in line:

`468  mrpt_bridge::convert(timeLastUpdate_, stamp);`

is changing also the value which at the end will be .1 and will throw the error of extrapolation. To fix it, I just set the time of the msg directly to that variable in method EKFslamWrapper::landmarkCallback

`timeLastUpdate_ = _msg.header.stamp.toSec();`

and then use it to initialize a ros::Time in the EKFslamWrapper::publishTF method:

`ros::Time stamp(timeLastUpdate_);`

with that, now, it can get the transformation. Let me know if that is that a correct way to fix it.

Best,

**Comment by Logrus** [comment]
Hi andrestoga,

Thanks for looking into this! Unfortunately I've been pilled up with other things and couldn't look up what is the problem myself.
Your solution seems reasonable, please fill free to make a pull request, I'd be happy to review and merge your changes.

Best,
Vladislav

**Comment by Logrus** [comment]
The problem occurred because tf transform were published even when no new robot poses were computed. It should be fixed right now.

**Comment by ayrmoney** [comment]
Hi @Logrus @andrestoga, I am now facing this issue,

`[ INFO] [1678040497.655616182]: Failed to subtract global_frame (map) from odom_frame (odom)`

and when I comment the try and catch code for the error, I get the following tf2::ExtrapolationException, which makes me feel I'm not publishing the transforms properly...

I am publishing map frame with a static transform publisher and sending the odom frame at ~100Hz.

```
terminate called after throwing an instance of 'tf2::ExtrapolationException'
  what():  Lookup would require extrapolation into the past.  Requested time 143265664.000032765 but the earliest data is at time 1677879818.100020647, when looking up transform from frame [base] to frame [odom]
```

and due to this (I guess) the orientation of the car that I get from the topic `/state_viz` is almost opposite to what it should be.... (as shown in the screenshot below). Any help or insight to help me solve this issue would be much appreciated.

![Screenshot from 2023-03-06 00-25-09](https://user-images.githubusercontent.com/87804122/222980197-e2e63d0c-4939-4ec6-8d3a-f8d976da9bd1.png)
