### ISSUE TITLE
Don't save .simplemap when using mrpt_rbpf_slam

### ISSUE THREAD

**Issue by dohema** [mrpt-ros-pkg/mrpt_slam#37]
hello,i have seen that in node destructor,it will try to save a .simplemap file,but i doubt whether the destructor will excute when the node ends,cause you write while(ros::ok()).
and in my test,no matter i use ctrl+c to stop the code,or wait for it ends by itself,it doesn't excute the destructor function

**Comment by jlblancoc** [comment]
Hi, 
Have you looked inside the `.ros` folder for the output `.simplemap` file?

**Comment by Logrus** [comment]
The non-intuitive behavior of saving *.simplemap is hopefully fixed by this:
https://github.com/mrpt-ros-pkg/mrpt_slam/pull/55/commits/86a622ebb8d5b733aaee5f65ef5c66a83f8a8130

Now by default all *.simplemap results will be saved in /tmp folder (please be aware all contents of this folder are purged between computer restarts). User can also specify an absolute path to the desired folder.
